Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-02, with the labels that each got.

#75 Pre-cache version field changes from ocp-release to sha-256 container image digests
  config/pre-cache/README.md
  config/pre-cache/overrides.yaml
  controllers/precache.go
  samples/clustergroupupgrade1.yaml
  samples/clustergroupupgrade3.yaml
  samples/precache/README.md
  samples/precache/cluster-version-policy.yaml
Labels: lgtm, approved, ok-to-test

#69 Support actions before/after upgrade
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  config/rbac/role.yaml
  controllers/actions.go
  controllers/actions_test.go
  controllers/clustergroupupgrade_controller.go
  controllers/managedclusterForCGU_controller.go
  controllers/managedclusterForCGU_controller_test.go
  controllers/utils/policy_util.go
Labels: lgtm, approved

#74 Update precache image tag in csv
  Makefile
  hack/patch-precache-image.py
Labels: lgtm, approved

#72 [BZ#2034625] Approve InstallPlan for Subscription type policies
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  child.policy5_all_sub_policy.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
  controllers/utils/multicloud_util.go
  deploy/acm/crds/action.open-cluster-management.io_managedclusteractions.yaml
  deploy/acm/crds/view.open-cluster-management.io_managedclusterviews.yaml
  deploy/acm/policies/patch-policies-status.sh
  go.mod
  go.sum
  main.go
  tests/pkg/client/clients.go
Labels: lgtm, approved

#80 Fix precache readme links and kustomization
  pre-cache/README.md
  samples/precache/README.md
  samples/precache/kustomization.yaml
Labels: lgtm, approved

#82 Bug 2050918: fix RBAC
  bundle.Dockerfile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manifests/pre-cache-image-patch.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#83 Fix related images yaml format
  config/manifests/pre-cache-image-patch.yaml
  hack/patch-precache-image.py
Labels: lgtm, approved

#84 Bug 2050918: Add configmaps to rbac
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#70 Include the possibility to use podman and docker as container engine
  Makefile
Labels: lgtm, approved, ok-to-test

#86 Fix policy content parsing
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#88 Update sample manifests
  samples/clustergroupupgrade1.yaml
  samples/clustergroupupgrade2.yaml
  samples/clustergroupupgrade3.yaml
  samples/upgrade-policy.yaml
Labels: lgtm, approved

#87 Add KUTTL test for operator upgrade
  deploy/acm/policies/all_policies/child-policy5-subscriptions.yaml
  deploy/acm/policies/all_policies/policy5-subscriptions.yaml
  deploy/upgrades/operator-upgrade/cgu-operator-upgrade.yaml
  deploy/upgrades/operator-upgrade/cleanup.sh
  deploy/upgrades/operator-upgrade/patch-install-plan-mcv-status.sh
  deploy/upgrades/operator-upgrade/patch-policies-status.sh
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-setup.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-start-upgrade.yaml
  tests/kuttl/tests/operator-upgrade/02-accept-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/03-cleanup.yaml
Labels: lgtm, approved

#90 Filter out the copied child policies
  controllers/clustergroupupgrade_controller.go
  controllers/managedclusterForCGU_controller.go
  controllers/managedclusterForCGU_controller_test.go
  controllers/utils/policy_util.go
Labels: lgtm, approved

#92 Bug 2056375: Allow clusterserviceversion access
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#96 Add cleanup finalizer for ClusterGroupUpgrade CRs
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
  controllers/utils/multicloud_util.go
Labels: lgtm, approved
