Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-08, with the labels that each got.

#275 Bug 2087125: Fix isUpgradeComplete() for previous batches
  controllers/clustergroupupgrade_controller.go
  deploy/acm/policies/upgrade_complete/patch-policies-status-batch1.sh
  deploy/acm/policies/upgrade_complete/patch-policies-status-batch2.sh
  deploy/upgrades/upgrade-complete/cgu-upgrade-complete.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-setup.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-complete-batch1.yaml
  tests/kuttl/tests/upgrade-complete/03-assert.yaml
  tests/kuttl/tests/upgrade-complete/03-complete-batch2.yaml
  tests/kuttl/tests/upgrade-complete/04-cleanup-upgrade-complete.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#274 Enhancement CNF-5302: Do not apply any changes after timeout has elapsed
  README.md
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#276 Bug 2109961: Run before enable actions even if all clusters are already compliant with cgu policy
  controllers/clustergroupupgrade_controller.go
  deploy/upgrades/upgrade-starts-complete/cgu-upgrade-starts-complete.yaml
  tests/kuttl/tests/upgrade-starts-complete/00-assert.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#282 Bug 2115898: Prometheus needs extra permissions (RBAC) for metrics
  bundle/manifests/cluster-group-upgrades-prometheus-metrics-reader_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/cluster-group-upgrades-prometheus-metrics-reader_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/prometheus/monitor.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#285 Bug 2115480: Fix batch timeout calculation for first batch
  controllers/clustergroupupgrade_controller.go
  controllers/utils/batches.go
  controllers/utils/batches_test.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#277 Enhancement CNF-3932: Configurable action on batch timeout
  api/v1alpha1/clustergroupupgrade_types.go
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#284 [release-4.10] Bug 2116401: Cherry pick Run before enable actions even if all clusters are already compliant with cgu policy
  controllers/clustergroupupgrade_controller.go
  deploy/upgrades/upgrade-starts-complete/cgu-upgrade-starts-complete.yaml
  tests/kuttl/tests/upgrade-starts-complete/00-assert.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#295 CNF-5043: Update README for managedclusterForCGU controller
  README.md
Labels: lgtm, approved

#294 Bug 2117581: Fix the auto-created CGU when a policy has "." in its name
  controllers/clustergroupupgrade_controller.go
  controllers/managedclusterForCGU_controller.go
  controllers/managedclusterForCGU_controller_test.go
  controllers/utils/policy_util.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#296 Bug 2115480: Reconcile immediately after timeout
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#298 [release-4.10] CNF-5043: Update README for managedclusterForCGU controller
  README.md
Labels: lgtm, approved

#264 [release-4.10] Bug 2108692: Check all batches for upgrade complete
  controllers/clustergroupupgrade_controller.go
  deploy/acm/policies/upgrade_complete/patch-policies-status-batch1.sh
  deploy/acm/policies/upgrade_complete/patch-policies-status-batch2.sh
  deploy/upgrades/upgrade-complete/cgu-upgrade-complete.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-setup.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-complete-batch1.yaml
  tests/kuttl/tests/upgrade-complete/03-assert.yaml
  tests/kuttl/tests/upgrade-complete/03-complete-batch2.yaml
  tests/kuttl/tests/upgrade-complete/04-cleanup-upgrade-complete.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#293 Enhancement CNF-4565: Do not create empty fields for managed policies that do not have appropriate content
  controllers/clustergroupupgrade_controller.go
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
Labels: lgtm, approved

#292 [release-4.10] Enhancement CNF-5302: Do not apply any changes after timeout has elapsed (Cherry Pick)
  README.md
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#303 Follow redirects when downloading operator-sdk tool
  Makefile
Labels: lgtm, approved
