Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-11, with the labels that each got.

#372 Lock ginkgo/gomega version
  hack/install-integration-tests-deps.sh
Labels: lgtm, approved

#371 OCPBUGS-2657: CGU Insufficient disk space to create backup
  Makefile
  recovery/cmd/backup_size.go
  recovery/cmd/backup_size_test.go
Labels: lgtm, approved

#378 OCPBUGS-3202: Fix issue with out of range / nil pointer after CGU timeout
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#379 OCPBUGS-3286: Skip clusters not on subscription policies properly
  controllers/monitoring.go
Labels: lgtm, approved

#380 OCPBUGS-3308: Skip clusters not on subscription policies properly
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#381 OCPBUGS-3212: Defer MCV creation for monitored objects
  controllers/clustergroupupgrade_controller.go
  controllers/monitoring.go
  controllers/utils/multicloud_util.go
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  kuttl-test.yaml
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-start-upgrade.yaml
  tests/kuttl/tests/operator-upgrade/02-add-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/03-accept-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/03-assert.yaml
  tests/kuttl/tests/operator-upgrade/04-cleanup.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
Labels: lgtm, approved

#384 OCPBUGS-3371: Defer MCV creation for monitored objects (#381)
  controllers/clustergroupupgrade_controller.go
  controllers/utils/multicloud_util.go
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  kuttl-test.yaml
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-complete-cgu-c-upgrade.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-start-upgrade.yaml
  tests/kuttl/tests/operator-upgrade/02-add-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/03-accept-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/03-assert.yaml
  tests/kuttl/tests/operator-upgrade/04-cleanup.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-complete-batch1.yaml
  tests/kuttl/tests/upgrade-complete/03-complete-batch2.yaml
Labels: lgtm, approved

#385 Bug 2115963: Add explicit error message for when no cluster selection methods are defined
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#383 OCPBUGS-2072: Precaching/backup resource cleanup
  controllers/actions.go
  controllers/backup.go
  controllers/clustergroupupgrade_controller.go
  controllers/managedClusterResources.go
  controllers/precacheFsm.go
Labels: lgtm, approved

#386 Update version to 4.13
  Makefile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#387 OCPBUGS-3488: Defer MCV creation for monitored objects (#381) (#384)
  controllers/clustergroupupgrade_controller.go
  controllers/utils/multicloud_util.go
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  kuttl-test.yaml
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-complete-cgu-c-upgrade.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-start-upgrade.yaml
  tests/kuttl/tests/operator-upgrade/02-add-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/03-accept-install-plan.yaml
  tests/kuttl/tests/operator-upgrade/03-assert.yaml
  tests/kuttl/tests/operator-upgrade/04-cleanup.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-complete-batch1.yaml
  tests/kuttl/tests/upgrade-complete/03-complete-batch2.yaml
Labels: lgtm, approved

#393 OCPBUGS-4079:RBAC permissions are not granted for ServiceMonitor CR...
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#260 [release-4.10] Bug 2102263: Controller metrics not exposed/collected …
  bundle/manifests/cluster-group-upgrades-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  config/default/kustomization.yaml
  manifests/stable/cluster-group-upgrades-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#394 OCPBUGS-4197: Handle error responses from upgrade graph server
  controllers/precache.go
Labels: lgtm, approved
