Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-03, with the labels that each got.

#99 Remove leftover manifest from local testing
  child.policy5_all_sub_policy.yaml
Labels: lgtm, approved

#101 Remove templates.go file
  controllers/templates.go
Labels: lgtm, approved

#102 Allow precaching to obtain compliant managed policies
  controllers/clustergroupupgrade_controller.go
  controllers/precacheFsm.go
Labels: lgtm, approved

#97 Bug 2058414: Support ClusterVersion without "desiredUpdate"
  controllers/precache.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#103 Remove unused code
  tests/pkg/utils/constants.go
  tests/unit-tests/suite_test.go
Labels: lgtm, approved

#106 Fix gosimple violations
  controllers/clustergroupupgrade_controller.go
  controllers/utils/multicloud_util.go
Labels: lgtm, approved

#100 BZ #2055309 - Include PKI folder when precaching against untrusted registries
  pre-cache/copy-env.sh
  pre-cache/olm
Labels: lgtm, approved, ok-to-test

#79 Add Daniel Mellado to OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, ok-to-test

#114 Improving precache duration by running simultaneous pull tasks
  pre-cache/common
  pre-cache/pull
Labels: lgtm, approved, ok-to-test

#112 Update Makefile to support PATH containing spaces
  Makefile
Labels: lgtm, approved

#115 Pre-caching: Add checks for return values
  pre-cache/olm
Labels: lgtm, approved

#116 Add license
  LICENSE
Labels: lgtm, approved

#117 Add failed recovery field to the CRD
  .gitignore
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
Labels: lgtm, approved

#118 Copy registries.conf in precache container for mirrored registry
  pre-cache/copy-env.sh
Labels: lgtm, approved, ok-to-test

#120 Add don and sabbir to owners
  OWNERS_ALIASES
Labels: lgtm, approved

#121 Fix typo in README
  README.md
Labels: lgtm, approved

#128 Build image using vendor folder
  Dockerfile
Labels: lgtm, approved

#127 Add upgrade recovery documentation
  recovery/HACKING.md
  recovery/README.md
Labels: lgtm, approved

#125 Introduce upgrade recovery tool
  .shellcheckrc
  Makefile
  hack/shellcheck.sh
  recovery/bindata/upgrade-recovery.sh
  recovery/generated/zz_generated.bindata.go
Labels: lgtm, approved

#124 new templates folder for pre-cache and backup job templates
  controllers/managedClusterResources.go
  controllers/precache.go
  controllers/templates/backup-templates.go
  controllers/templates/precache-templates.go
Labels: lgtm, approved

#113 Add golangci-lint
  .golangci.yml
  Makefile
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
  controllers/managedclusterForCGU_controller.go
  controllers/precache.go
  controllers/precacheFsm.go
  controllers/templates/backup-templates.go
  controllers/templates/precache-templates.go
  controllers/utils/common.go
  controllers/utils/constants.go
  controllers/utils/multicloud_util.go
  hack/golangci-lint.sh
  hack/update-deps.sh
  recovery/cmd/launchBackup.go
  recovery/cmd/root.go
Labels: lgtm, approved

#81 Add universal index processing
  pre-cache/olm
  pre-cache/parse_index.py
Labels: lgtm, approved

#131 [cnf-4257] precaching implementation reorganization for reusability
  controllers/managedClusterResources.go
  controllers/precache.go
  controllers/precacheFsm.go
Labels: lgtm, approved

#139 Delete cgu-controller-manager serviceAccount yaml.
  bundle.Dockerfile
  bundle/manifests/cluster-group-upgrades-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
Labels: lgtm, approved

#138 Add verify-bindata and shellcheck to ci-job
  Makefile
  hack/shellcheck.sh
Labels: lgtm, approved

#140 Fix docker pull secret path
  pre-cache/copy-env.sh
Labels: lgtm, approved
