Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-07, with the labels that each got.

#243 Add operator-sdk version check to Makefile
  Makefile
Labels: lgtm, approved

#240 Bug 2102743: RBAC permissions are not granted for ServiceMonitor CR
  config/rbac/role.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#245 [release-4.10] Add operator-sdk version check to Makefile (#243)
  Makefile
Labels: lgtm, approved

#248 Revert "BZ 2102743: RBAC permissions are not granted for ServiceMoni…
  config/rbac/role.yaml
Labels: lgtm, approved

#246 Update generated files for version change
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved

#249 Add check of bundle generated files to ci-job
  Makefile
  hack/check-git-tree.sh
Labels: lgtm, approved

#228 Requeue immediately when moving to the next batch
  .gitignore
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#253 Add retry to golangci-lint installation
  hack/golangci-lint.sh
Labels: lgtm, approved

#255 Bug 2105992: Fix batch timeout calculation units (and add unit tests)
  controllers/clustergroupupgrade_controller.go
  controllers/utils/batches.go
  controllers/utils/batches_test.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#257 Bug 2087125: Check all batches for upgrade complete
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#259 [release-4.10] Bug 2106114: Fix batch timeout calculation units (and add unit tests)
  controllers/clustergroupupgrade_controller.go
  controllers/utils/batches.go
  controllers/utils/batches_test.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#262 Enhancement CNF-5558: Add new method for specifying clusters for CGU
  .gitignore
  Makefile
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  controllers/clustergroupupgrade_controller.go
  deploy/upgrades/cluster-selector/cgu-cluster-selector.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
Labels: lgtm, approved

#265 Bug 2106101: Shorter requeue interval on approving installplan
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#269 Replace "go get" with "go install" in Makefile
  Makefile
Labels: lgtm, approved

#270 BUG 2107695: Update recovery README with wipeTable warning
  docs/backup-recovery/README.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#261 [release-4.11] Bug 2106287: RBAC permissions are not granted for Servi…
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#268 Bug 2106083: Requeue after logging fix
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#266 Bug 2077974: Prevent reconcile error when policy status is missing
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#271 Bug 2079502: Exclude generated policy from cluster-backup-operator
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
