Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-04, with the labels that each got.

#141 Enable shellcheck for all .sh scripts
  deploy/upgrades/operator-upgrade/cleanup.sh
  hack/install-integration-tests-deps.sh
  hack/shellcheck.sh
  pre-cache/copy-env.sh
  pre-cache/test.sh
Labels: lgtm, approved

#136 Fix OLM index extraction
  pre-cache/common
  pre-cache/copy-env.sh
  pre-cache/olm
Labels: lgtm, approved

#137 Properly update policy/placement binding/rule objects
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, ok-to-test

#143 Enable bashate style checker
  Makefile
  deploy/acm/policies/cluster_selector/apply_policies.sh
  deploy/upgrades/operator-upgrade/cleanup.sh
  hack/bashate.sh
  hack/lint.sh
  hack/shellcheck.sh
  pre-cache/copy-env.sh
  pre-cache/precache.sh
  pre-cache/test.sh
Labels: lgtm, approved

#146 Ignore policies that have remediationAction enforce
  controllers/clustergroupupgrade_controller.go
  controllers/managedclusterForCGU_controller.go
Labels: lgtm, approved

#147 Use builtin client in createResourcesFromTemplates
  controllers/managedClusterResources.go
Labels: lgtm, approved

#148 Ignore bin and testbin dirs for bash linters
  hack/bashate.sh
  hack/shellcheck.sh
Labels: lgtm, approved

#152 Bug 2073144: Cherry pick #137
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#144 [ CNF-4622 ] - Trigger backup task and reconcile with the controller
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/backup.go
  controllers/clustergroupupgrade_controller.go
  controllers/managedClusterResources.go
  controllers/precache.go
  controllers/precacheFsm.go
  controllers/templates/backup-templates.go
Labels: lgtm, approved

#157 Add precaching pull spec as env var
  Makefile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/related-images/.gitignore
  config/manager/related-images/in.yaml
  config/manifests/kustomization.yaml
  config/manifests/pre-cache-image-patch.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
  controllers/precache.go
  hack/patch-precache-image.py
  samples/precache/README.md
Labels: lgtm, approved

#155 Define precaching and backup images as env vars
  Makefile
  config/manager/kustomization.yaml
  config/manager/related-images/.gitignore
  config/manager/related-images/in.yaml
  config/manifests/kustomization.yaml
  config/manifests/pre-cache-image-patch.yaml
  config/manifests/recovery-image-patch.yaml
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
  controllers/precache.go
  hack/patch-bundle-images.py
  samples/precache/README.md
Labels: lgtm, approved

#159 Bug 2074236: Performance fixes for ZTP scale test
  controllers/clustergroupupgrade_controller.go
  controllers/utils/multicloud_util.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#161 Update operator bundle icon
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#163 Add icon to the CSV
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#162 Bug 2075134: Performance fixes for ZTP scale test
  controllers/clustergroupupgrade_controller.go
  controllers/utils/multicloud_util.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#160 cleanup backup view and job if upgrade succeeds
  controllers/clustergroupupgrade_controller.go
  controllers/managedClusterResources.go
Labels: lgtm, approved

#151 Add pre-caching unit tests
  Makefile
  controllers/managedClusterResources.go
  controllers/managedClusterResources_test.go
  controllers/overrides_test.go
  controllers/precache.go
  controllers/precacheFsm.go
  pre-cache/test.sh
Labels: lgtm, approved

#156 remove null fields for precaching from api response
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/backup.go
  controllers/clustergroupupgrade_controller.go
  controllers/precache.go
  controllers/precacheFsm.go
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/01-assert.yaml
Labels: lgtm, approved

#166 Reduce custom scorecard test to minimum
  config/scorecard/kustomization.yaml
Labels: lgtm, approved

#165 Bug 2075676: Fix make deploy target
  Makefile
  README.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#168 Fix make deploy target
  Makefile
  README.md
Labels: lgtm, approved

#170 add annotations and rebuild bundle to fix scorecard tests
  api/v1alpha1/clustergroupupgrade_types.go
  bundle.Dockerfile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/samples/ran_v1alpha1_clustergroupupgrade.yaml
Labels: lgtm, approved

#171 add annotations to fix scorecard test failures
  api/v1alpha1/clustergroupupgrade_types.go
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/samples/ran_v1alpha1_clustergroupupgrade.yaml
  config/scorecard/kustomization.yaml
Labels: lgtm, approved

#169 Update readme
  README.md
  samples/blocking-mechanisms.yaml
  samples/cluster-selector.yaml
  tests/README.md
Labels: lgtm, approved

#174 set image field from environment variable
  api/v1alpha1/clustergroupupgrade_types.go
  controllers/backup.go
  controllers/managedClusterResources.go
  controllers/templates/backup-templates.go
Labels: lgtm, approved

#175 Make image tags consistent with upstream builds
  Makefile
  bundle.Dockerfile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#176 Bug 2079838: Make image tag consistent with u/s build
  Makefile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug
