Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-05, with the labels that each got.

#177 Add journald logging to upgrade recovery utility
  recovery/bindata/upgrade-recovery.sh
  recovery/generated/zz_generated.bindata.go
Labels: lgtm, approved

#178 recovery: Restore /var/lib/kubelet after reboot
  recovery/bindata/upgrade-recovery.sh
  recovery/generated/zz_generated.bindata.go
Labels: lgtm, approved

#181 Batch placement rule updates for multiple clusters
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#179 Bug 2081570: Batch placement rule updates for multiple clusters
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#145 Random suffix and smart truncation for talo created object names
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/clustergroupupgrade_controller.go
  controllers/utils/common.go
  controllers/utils/common_test.go
  controllers/utils/constants.go
  controllers/utils/multicloud_util.go
  controllers/utils/multicloud_util_test.go
  controllers/utils/policy_util.go
  deploy/upgrades/adjust-max-concurrency/cgu-adjust-max-concurrency.yaml
  deploy/upgrades/blocking-mechanisms/cgu-a.yaml
  deploy/upgrades/blocking-mechanisms/cgu-b.yaml
  deploy/upgrades/blocking-mechanisms/cgu-c.yaml
  deploy/upgrades/cgu-upgrade-complete.yaml
  deploy/upgrades/cluster-selector/cgu-cluster-selector.yaml
  deploy/upgrades/operator-upgrade/cgu-operator-upgrade.yaml
  deploy/upgrades/operator-upgrade/patch-install-plan-mcv-status.sh
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  deploy/upgrades/policy-has-missing-cluster-status/cgu.yaml
  deploy/upgrades/skip-compliant-policies/skip-compliant-policies.yaml
  deploy/upgrades/upgrade-starts-complete/cgu-upgrade-starts-complete.yaml
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/01-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
Labels: lgtm, approved

#184 Add Bugzilla component info to OWNERS file
  OWNERS
Labels: lgtm, approved

#185 Bug 2072039: Execute post upgrade actions once only
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#187 Bug 2083387: Execute post upgrade actions once only
  controllers/clustergroupupgrade_controller.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#188 Bug 2083631 Reset batch start time on batch timeout
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#189 Bug 2083800: Reset batch start time on batch timeout
  controllers/clustergroupupgrade_controller.go
Labels: bugzilla/severity-high, bugzilla/valid-bug

#190 Enable disconnected features
  Makefile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#198 Add image-references file
  manifests/image-references
Labels: lgtm, approved
