Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2022-06, with the labels that each got.

#201 Bug 2091616: Unable to start upgrade with backup enabled with "Reconciler error"
  controllers/clustergroupupgrade_controller.go
  controllers/managedClusterResources_test.go
  controllers/templates/precache-templates.go
  controllers/utils/constants.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#196 Bump golangci-lint version to 1.46.1
  hack/golangci-lint.sh
Labels: lgtm, approved

#193 Add Upgrade State printer column for CGU
  api/v1alpha1/clustergroupupgrade_types.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
Labels: lgtm, approved, ok-to-test

#191 Fix crashing on policies with no annotations
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, ok-to-test

#203 Bug 2091113: Query child resources only when new ones are being created
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#195 Improve batch progress state
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/01-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
Labels: lgtm, approved

#212 Update image-references with new image names
  manifests/image-references
Labels: lgtm, approved

#210 Bug 2094413: Random suffix for TALO created object names
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/clustergroupupgrade_controller.go
  controllers/utils/common.go
  controllers/utils/common_test.go
  controllers/utils/constants.go
  controllers/utils/multicloud_util.go
  controllers/utils/multicloud_util_test.go
  controllers/utils/policy_util.go
  deploy/upgrades/adjust-max-concurrency/cgu-adjust-max-concurrency.yaml
  deploy/upgrades/blocking-mechanisms/cgu-a.yaml
  deploy/upgrades/blocking-mechanisms/cgu-b.yaml
  deploy/upgrades/blocking-mechanisms/cgu-c.yaml
  deploy/upgrades/cgu-upgrade-complete.yaml
  deploy/upgrades/cluster-selector/cgu-cluster-selector.yaml
  deploy/upgrades/operator-upgrade/cgu-operator-upgrade.yaml
  deploy/upgrades/operator-upgrade/patch-install-plan-mcv-status.sh
  deploy/upgrades/operator-upgrade/patch-sub-mcv-status.sh
  deploy/upgrades/policy-has-missing-cluster-status/cgu.yaml
  deploy/upgrades/skip-compliant-policies/skip-compliant-policies.yaml
  deploy/upgrades/upgrade-starts-complete/cgu-upgrade-starts-complete.yaml
  tests/kuttl/tests/adjust-max-concurrency/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/00-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/cluster-selector/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/00-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/operator-upgrade/02-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/00-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/01-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#213 Bug 2090842: Improve event filtering with proper type check
  api/v1alpha1/clustergroupupgrade_types.go
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#216 Bug 2095811: Proper event filtering and cluster progress field improvement
  api/v1alpha1/clustergroupupgrade_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  config/crd/bases/ran.openshift.io_clustergroupupgrades.yaml
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
  controllers/utils/constants.go
  tests/kuttl/tests/blocking-mechanisms/01-assert.yaml
  tests/kuttl/tests/blocking-mechanisms/02-assert.yaml
  tests/kuttl/tests/operator-upgrade/01-assert.yaml
  tests/kuttl/tests/policy-has-missing-cluster-status/01-assert.yaml
  tests/kuttl/tests/skip-compliant-policies/00-assert.yaml
  tests/kuttl/tests/upgrade-complete/01-assert.yaml
  tests/kuttl/tests/upgrade-complete/02-assert.yaml
Labels: lgtm, approved, bugzilla/severity-high, bugzilla/valid-bug

#218 Release 4.10 update operator-sdk
  Makefile
  bundle.Dockerfile
  bundle/manifests/cluster-group-upgrades-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  bundle/manifests/ran.openshift.io_clustergroupupgrades.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  manifests/stable/cluster-group-upgrades-operator.clusterserviceversion.yaml
  manifests/stable/ran.openshift.io_clustergroupupgrades.yaml
Labels: lgtm, approved

#219 Remove serviceaccount file from manifests/stable
  manifests/stable/cluster-group-upgrades-controller-manager_v1_serviceaccount.yaml
Labels: lgtm, approved

#222 Bug 2084664: Add missing RBAC permissions to allow creating and patching of events
  config/rbac/role.yaml
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#220 Update the default version tag
  Makefile
Labels: lgtm, approved

#227 Enhancement CNF-5013: Delete precaching objects on final cleanup
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#223 update recovery utility in the documentation
  docs/backup-recovery/README.md
Labels: lgtm, approved

#231 Align image-references and CSV for ART build
  manifests/stable/image-references
Labels: lgtm, approved

#232 Minor cleanup missed in commit 7a2463
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#226 Enhancement CNF-5294: Improve batch timeout calculation to use the remaining time for calculating the remaining timeout
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#229 Bug 2086921: Controller metrics not exposed/collected properly...
  bundle/manifests/cluster-group-upgrades-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  config/default/kustomization.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#230 add script from midstream repo for updating CSV to match downstream name
  bundle/render_templates
  bundle/render_vars.in
Labels: lgtm, approved

#238 Enhancement CNF-5013: Make CGU resource cleanup more consistent
  controllers/actions.go
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#237 Enhancement ENF-5294: Fix batch timeout calculation to always account for remaining time
  controllers/clustergroupupgrade_controller.go
Labels: lgtm, approved

#235 Update version tag to 4.12.0
  Makefile
Labels: lgtm, approved

#241 CSV configuration updates for ART in release-4.10
  bundle/render_templates
  bundle/render_vars.in
  manifests/art.yaml
  manifests/cluster-group-upgrades-operator.package.yaml
  manifests/stable/topology-aware-lifecycle-manager.clusterserviceversion.yaml
  manifests/topology-aware-lifecycle-manager.package.yaml
Labels: lgtm, approved
