Repository openshift-kni/cluster-group-upgrades-operator, pull requests merged in 2025-04, with the labels that each got.

#1015 Add condition check to use FIPS compiling in Konflux builds
  Dockerfile
  Dockerfile.aztp
  Dockerfile.recovery
  build_args_konflux.conf
Labels: lgtm

#1014 Overlay clusterserviceversion at build time for Konflux
  .tekton/topology-aware-lifecycle-manager-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-19-push.yaml
  Makefile
  bundle.konflux.Dockerfile
  hack/konflux_update_task_refs.sh
  konflux_build_args.conf
  konflux_clusterserviceversion_overlay.data
  konflux_clusterserviceversion_overlay.sh
  renovate.json
Labels: lgtm, do-not-merge/hold

#908 CNF-17432: IBGU: Cache only ManifestWorks that are created by TALM
  main.go
Labels: lgtm, approved

#1060 OCPBUGS-54738: Fix panic when cluster is not in current batch
  controllers/policy.go
  deploy/acm/policies/upgrade_complete/patch-policies-status-batch3.sh
  kuttl-test.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/00-assert.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/00-setup.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/01-assert.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/01-start-upgrade.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/02-assert.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/02-force-timeout.yaml
  tests/kuttl/cgu/timeout-not-block-next-batch/03-cleanup.yaml
Labels: lgtm, approved

#1056 Allow dependabot to create security updates for 4.18
  .github/dependabot.yml
Labels: lgtm, approved

#1084 Update renovate.json configuration
  renovate.json
Labels: lgtm, approved

#1085 Update overlay data usage
  konflux_clusterserviceversion_overlay.data
  konflux_clusterserviceversion_overlay.sh
Labels: lgtm

#1086 Upversion TALM to 4.20
  Makefile
  bundle/manifests/cluster-group-upgrades-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/cluster-group-upgrades-operator.clusterserviceversion.yaml
  tests/kuttl/cgu/backup-complete/02-assert.yaml
  tests/kuttl/cgu/backup-fail/02-assert.yaml
  tests/kuttl/cgu/backup-partial-complete/02-assert.yaml
  tests/kuttl/cgu/pre-caching-complete/03-assert.yaml
  tests/kuttl/cgu/pre-caching-partial-complete/03-assert.yaml
Labels: lgtm, approved

#1097 README update for new events and kuttl tcs
  README.md
  tests/kuttl/cgu/upgrade-batch-timeout/00-assert.yaml
  tests/kuttl/cgu/upgrade-batch-timeout/00-setup.yaml
  tests/kuttl/cgu/upgrade-batch-timeout/01-assert.yaml
  tests/kuttl/cgu/upgrade-batch-timeout/02-assert.yaml
  tests/kuttl/cgu/upgrade-batch-timeout/03-assert.yaml
  tests/kuttl/cgu/upgrade-batch-timeout/04-cleanup.yaml
  tests/kuttl/cgu/upgrade-complete/00-assert.yaml
  tests/kuttl/cgu/upgrade-complete/00-setup.yaml
  tests/kuttl/cgu/upgrade-complete/01-assert.yaml
  tests/kuttl/cgu/upgrade-complete/02-assert.yaml
  tests/kuttl/cgu/upgrade-complete/03-assert.yaml
  tests/kuttl/cgu/upgrade-complete/04-cleanup-upgrade-complete.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/00-assert.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/00-setup.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/01-assert.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/03-assert.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/04-assert.yaml
  tests/kuttl/cgu/upgrade-partial-batch-timeout/05-cleanup.yaml
Labels: lgtm, approved, ok-to-test

#1121 [release-4.19] Update Konflux target branch to release-4.19
  .tekton/topology-aware-lifecycle-manager-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-19-push.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-19-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-19-push.yaml
Labels: lgtm, approved

#1118 Upversion Konflux references from 4.19/4-19 to 4.20/4-20
  .tekton/build-pipeline.yaml
  .tekton/topology-aware-lifecycle-manager-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-20-push.yaml
  bundle.konflux.Dockerfile
  konflux_clusterserviceversion_overlay.data
Labels: lgtm, do-not-merge/hold

#1140 Disable gomod updates from renovate.json
  renovate.json
Labels: lgtm, approved

#1159 Update `on-cel-expression` values for tekton pipelines to limit unnecessary builds
  .tekton/topology-aware-lifecycle-manager-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-aztp-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-bundle-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-precache-4-20-push.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-20-pull-request.yaml
  .tekton/topology-aware-lifecycle-manager-recovery-4-20-push.yaml
Labels: lgtm, approved
